---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - bower_components

before_install:
  - npm config set spin false
  - yarn global add bower
  - bower --version
  - yarn add phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - yarn install
  - bower install

script:
  - yarn test

branches:
  only:
    - master
